# Generated by Django 4.0.2 on 2022-02-27 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_options_alter_post_reading_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subheading',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
