# Generated by Django 4.0.2 on 2022-02-27 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_subheading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(help_text='The markdown tool is available.'),
        ),
        migrations.AlterField(
            model_name='post',
            name='subheading',
            field=models.TextField(help_text='The markdown tool is available.'),
        ),
    ]
